### ISSUE TITLE
Failing to detect a new major version

### ISSUE THREAD

**Issue by iwahbe** [pulumi/upgrade-provider#218]
### What happened?

We ran this workflow: https://github.com/pulumi/pulumi-minio/actions/runs/7225716362/job/19689733780, reporting no new upgrade targets:
<img width="1316" alt="Screenshot 2023-12-15 at 11 01 36 AM" src="https://github.com/pulumi/upgrade-provider/assets/22222529/8b3ee831-5aa2-4a7b-af93-b165e6f23221">

However, we were on a `v1` version, while upstream was on a `v2` version.

### Example

NA

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Yup, I can reproduce this:
```
gh release list --repo=aminueza/terraform-provider-minio --limit=1 --exclude-drafts --exclude-pre-releases
TITLE    TYPE  TAG NAME  PUBLISHED
v1.20.1        v1.20.1   about 1 month ago
```
However:

```
 gh release list --repo=aminueza/terraform-provider-minio --exclude-drafts --exclude-pre-releases
TITLE    TYPE    TAG NAME  PUBLISHED
v1.20.1          v1.20.1   about 1 month ago
v2.0.1   Latest  v2.0.1    about 1 month ago
v2.0.0           v2.0.0    about 1 month ago
v1.20.0          v1.20.0   about 1 month ago
v1.19.0          v1.19.0   about 1 month ago
v1.18.3          v1.18.3   about 1 month ago
v1.18.0          v1.18.0   about 3 months ago
v1.17.2          v1.17.2   about 4 months ago
v1.17.1          v1.17.1   about 4 months ago
v1.17.0          v1.17.0   about 4 months ago
```

This is because the v1.20.1 tag and the v2.0.1 tags are at the same commit. This issue is likely limited to providers that tag the same commit with valid stable semver.

The GH CLI does not have a flag on `release` for requesting `latest`. However, we [have a method that does more reliably detect the latest release, from the repo info payload](https://github.com/pulumi/upgrade-provider/blob/main/upgrade/steps_helpers.go#L407) and we should use that logic in https://github.com/pulumi/upgrade-provider/blob/main/upgrade/steps_helpers.go#L514 instead.
