### ISSUE TITLE
Tool deleted all my plugins

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/upgrade-provider#88]
### What happened?

I had a bunch of plugins installed. The tool ran `pulumi plugin rm --all`

This wasn't ideal. It even deleted my language plugins.

### Expected Behavior

It doesn't delete all my plugins

### Steps to reproduce

Run the tool

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
We sometimes get odd behavior because of old versions of plugins being sticky, and when bulk updating, it's often not clear which plugins are dependencies.

That said, I agree this is not ideal. A solution could be to identify when an update fails because of an older plugin, and at that point send an error to the user, prompting them to delete plugins. 

We could also make this an optional flag, or, opposite, create an opt-out flag.

Alternately, you can try using the [GHA](https://github.com/pulumi/pulumi-upgrade-provider-action), where presumably the runner won't have any plugins to remove.

**Comment by t0yv0** [comment]
Should consider looking at why plugins are deleted in the first place and fixing the root cause so they don't have to be deleted.
